name: On Commit

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v31

      - name: Lint
        run: nix develop -c just lint

      - name: Test
        run: nix develop -c just test
